name: main

on: 
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: true
        default: 'test'

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Rodrigo"
      
      - name: script
        run: |
          chmod +x script.sh
          ./script.sh

      - name: Notification
        uses: rtCamp/action-slack-notify@v2.3.2
        env:
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        with:
          author_name: "Action"
          fields: repo, message, commit, author, action, eventName
