name: main

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Hola
        run: |
          echo "Hola Mundo" >> hola.txt
          cat hola.txt
      
      - name: script
        run: |
          chmod +x script.sh
          ./script.sh